import { AtsAnalysis, ResumeData, WizardInitialData, CareerRoadmapResponse } from "../types";

// Mocking AI service for frontend migration phase
// Real implementation will move to /app/api/ai/route.ts later

export const analyzeAtsScore = async (resumeText: string, jobDescription?: string): Promise<AtsAnalysis> => {
  console.log("AI Service: analyzeAtsScore called (Mock)");
  return {
    overallScore: 85,
    contentQuality: 80,
    atsStructure: 90,
    jobOptimization: 75,
    writingQuality: 88,
    applicationReady: 85,
    summary: "AI features are disabled during the migration to Next.js. This is a mock response.",
    improvements: ["Enable the AI backend", "Configure OpenRouter API key"]
  };
};

export const parseRawResumeData = async (resumeText: string): Promise<WizardInitialData> => {
  console.log("AI Service: parseRawResumeData called (Mock)");
  return {
    personalInfo: {
      fullName: "Migration User",
      email: "mock@example.com",
      phone: "555-555-5555",
      location: "Mock City",
      linkedin: "linkedin.com/in/mock"
    },
    experienceRaw: "Mock experience",
    educationRaw: "Mock education",
    skillsRaw: "Mock skills"
  };
};

export const tailorResume = async (currentResumeData: ResumeData, jobDescription: string): Promise<string> => {
  return "# Tailored Resume (Mock)\n\nAI features are currently disabled.";
};

export const generateClarificationQuestions = async (inputs: any): Promise<string[]> => {
  return ["Why is the AI disabled?", "When will it be back?", "Is this Next.js?"];
};

export const generateFullResume = async (inputs: any, clarificationAnswers?: any): Promise<any> => {
  throw new Error("AI Disabled");
}

export const optimizeResumeContent = async (currentResume: string, jobDescription: string): Promise<string> => {
  return "Use tailorResume instead";
};

export const roastMyResume = async (resumeText: string, persona: string = 'hr'): Promise<string> => {
  return "**Roast Inactive**: I can't roast you right now, I'm being migrated to a new framework.";
};

export const generateResumeSummary = async (data: Partial<ResumeData>, targetRole: string): Promise<string> => {
  return "Professional Summary generated by AI (Mock).";
};

export const generateCareerRoadmap = async (data: ResumeData, targetRole: string): Promise<CareerRoadmapResponse | null> => {
  return null;
};

export const generateCoverLetter = async (data: ResumeData, jobDescription: string): Promise<string> => {
  return "Dear Hiring Manager,\n\nPlease hire me. (Mock Cover Letter)";
};